selenium-hub:
  image: selenium/hub
  ports:
    - 4545:4444

chromenode:
  image: selenium/node-chrome-debug
  ports:
    - 4445
  links:
    - selenium-hub:hub

firefoxnode:
  image: selenium/node-firefox-debug
  ports:
    - 4446
  links:
    - selenium-hub:hub
